### ISSUE TITLE
synapse-purge stoped working: matrix_sdk/extensions.rb:4:in `<module:URI>': uninitialized constant URI::Generic (NameError)

### ISSUE THREAD

**Issue by mnowiasz** [djmaze/synapse-purge#7]
I'm using synapse-purge for quite some time, and it worked quite well - but suddenly (can't pinpoint the exact date) it stopped working:

```
Traceback (most recent call last):
        5: from synapse-purge.rb:6:in `<main>'
        4: from synapse-purge.rb:6:in `require'
        3: from /home/matrix/.gem/ruby/2.5.0/gems/matrix_sdk-1.2.0/lib/matrix_sdk.rb:3:in `<top (required)>'
        2: from /home/matrix/.gem/ruby/2.5.0/gems/matrix_sdk-1.2.0/lib/matrix_sdk.rb:3:in `require'
        1: from /home/matrix/.gem/ruby/2.5.0/gems/matrix_sdk-1.2.0/lib/matrix_sdk/extensions.rb:3:in `<top (required)>'
/home/matrix/.gem/ruby/2.5.0/gems/matrix_sdk-1.2.0/lib/matrix_sdk/extensions.rb:4:in `<module:URI>': uninitialized constant URI::Generic (NameError)
```
Any ideas? The same error occured under ruby24, I've also tried a clean install, but no avail.

**Comment by djmaze** [comment]
I have pushed some fixes and pinned the Ruby version to 2.6 (which works). Please try with that or even use the docker image (recommended) at `decentralize/synapse-purge`.
